version: '3.8'

services:
    app:
        build: ./goodies-shop-webapi
        container_name: goodies-shop-webapi
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db/goodies_shop_db?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
            JWT_SECRET: secret
            JWT_ACCESS-TOKEN-EXPIRATION: 86400000
        networks:
            - goodies-shop-network
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: goodies-shop-db
        restart: always
        tty: true
        ports:
            - '13306:3306'
        environment:
            MYSQL_DATABASE: goodies_shop_db
            MYSQL_ROOT_PASSWORD: root
            MSYQL_USER: root
        networks:
            - goodies-shop-network
        volumes:
            - ./.docker/dbdata:/var/lib/mysql

networks:
    goodies-shop-network:
        driver: bridge
